"""Remove guides that are two names for the same subject, and redirect them (2-sep-2026).

    uv run python scripts/dedupe_guides.py            # report only
    uv run python scripts/dedupe_guides.py --apply    # delete and write the redirects

TOPIC_PLAN carries a Spanish-named and an English-named key for several subjects (hives and
urticaria, screen_sleep and sueno_pantallas, head_injury_en and traumatismo_craneal...). Publishing
both gives two nearly identical guides in the same language, which split the ranking between them.

The pairs come from SAME_SUBJECT in articles.py, which is a written-down list and not a heuristic.
Measuring the overlap of source documents was tried first and over-flagged: it wanted to delete
breastfeeding because of starting solids, and asthma because of an asthma attack. Losing one of
those costs a real guide, so the judgement is made once, by hand, and recorded.

The older guide stays — it is the one that may already have traffic — and the newer one becomes a
301 to it, written into a block of the Caddyfile that this script owns and rewrites in full.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CONTENT = ROOT / "web" / "content"
CADDY = ROOT / "ops" / "Caddyfile"
START = "\t# >>> guide redirects (generated by scripts/dedupe_guides.py — do not edit by hand)"
END = "\t# <<< guide redirects"


def same_subject_pairs() -> set[frozenset[str]]:
    """The declared pairs, not a guess. Measuring the overlap of source documents flagged guides
    that are genuinely different subjects (breastfeeding vs starting solids, asthma vs an asthma
    attack), and deleting one of those costs real content."""
    sys.path.insert(0, str(ROOT / "src"))
    from pedibot.publish.articles import SAME_SUBJECT

    return set(SAME_SUBJECT)


def published(lang: str) -> dict[str, tuple[pathlib.Path, str]]:
    """topic -> (file, date) for the guides of one language."""
    out: dict[str, tuple[pathlib.Path, str]] = {}
    for f in sorted((CONTENT / lang).glob("*.md")):
        text = f.read_text(encoding="utf-8")
        topic = re.search(r"^topic:\s*(\S+)", text, re.M)
        date = re.search(r"^date:\s*(\S+)", text, re.M)
        if topic:
            out[topic.group(1)] = (f, date.group(1) if date else "")
    return out


def plan(lang: str) -> list[tuple[pathlib.Path, str, str]]:
    """(file to remove, its slug, the slug that stays), keeping the older guide."""
    have = published(lang)
    moves = []
    for pair in same_subject_pairs():
        a, b = sorted(pair)
        if a not in have or b not in have:
            continue
        (fa, da), (fb, db) = have[a], have[b]
        keep, drop = (fa, fb) if (da, fa.stat().st_mtime) <= (db, fb.stat().st_mtime) else (fb, fa)
        moves.append((drop, drop.stem, keep.stem))
    return moves


def redirect_block(moves: dict[str, list[tuple[str, str]]]) -> str:
    lines = [START]
    for lang, items in moves.items():
        prefix = "/guides" if lang == "en" else "/es/guides"
        for gone, stays in sorted(items):
            lines.append(f"\tredir {prefix}/{gone} {prefix}/{stays} permanent")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    moves = {lang: [(d.stem, keep) for d, _, keep in plan(lang)] for lang in ("en", "es")}
    total = sum(len(v) for v in moves.values())
    for lang, items in moves.items():
        print(f"--- {lang}: {len(items)} duplicate(s)")
        for gone, stays in sorted(items):
            print(f"    {gone}  →  {stays}")
    if not args.apply or not total:
        print("\n(report only; pass --apply to remove them)" if total else "\nnothing to do")
        return 0

    for lang in ("en", "es"):
        for drop, _, _ in plan(lang):
            drop.unlink()
            q = ROOT / "publish" / "queue" / "x" / f"{lang}-{drop.stem}.txt"
            if q.exists():
                q.unlink()
            print("removed", drop.relative_to(ROOT))

    text = CADDY.read_text(encoding="utf-8")
    block = redirect_block(moves)
    if START in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        text = text.replace("\t# Static site (Astro build)", block + "\n\n\t# Static site (Astro build)", 1)
    CADDY.write_text(text, encoding="utf-8")
    print(f"\n{total} redirect(s) written into ops/Caddyfile")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
