"""Las direcciones viejas de las guías, en un solo sitio (16-sep-2026).

Una guía cambia de dirección cuando se regenera: el nombre del fichero sale del título y el
título cambia. Eso se conserva a propósito —así se arreglaron slugs mal transliterados como
«was_tun_bei_einer_erk_ltung»— pero la dirección vieja no puede morir: es lo que Google tiene
indexado y lo que alguien tiene enlazado.

Hasta hoy había DOS sitios donde vivía esa lista y ninguno los juntaba: un bloque escrito a mano
en `ops/Caddyfile` (con lo que reescribía `scripts/dedupe_guides.py`, que borraba lo que no
conociera) y, desde esta tarde, `web/content/_redirects.json`, que escribe el publicador cada vez
que renombra una guía. Ahora el JSON es la fuente y tiene dos consumidores:

- **Caddy**, que las sirve como 301 de verdad (lo que Google respeta sin discusión);
- **Astro**, que además genera la página vieja con su `canonical` para una copia local o una
  vista previa sin servidor delante.

    uv run python scripts/sync_redirects.py          # enseña lo que cambiaría
    uv run python scripts/sync_redirects.py --apply  # lo escribe en ops/Caddyfile
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CADDY = ROOT / "ops" / "Caddyfile"
REDIRECTS = ROOT / "web" / "content" / "_redirects.json"
START = "\t# >>> guide redirects (generated by scripts/sync_redirects.py — do not edit by hand)"
END = "\t# <<< guide redirects"


def leer() -> dict[str, str]:
    if not REDIRECTS.exists():
        return {}
    return dict(json.loads(REDIRECTS.read_text(encoding="utf-8")))


def paginas_vivas() -> set[str]:
    """Las guías que existen ahora mismo, por su dirección."""
    contenido = ROOT / "web" / "content"
    return {
        f"{'' if d.name == 'en' else '/' + d.name}/guides/{f.stem}"
        for d in contenido.iterdir()
        if d.is_dir()
        for f in d.glob("*.md")
    }


def bloque(mapa: dict[str, str]) -> str:
    lineas = [START]
    for viejo, nuevo in sorted(mapa.items()):
        lineas.append(f"\tredir {viejo} {nuevo} permanent")
    lineas.append(END)
    return "\n".join(lineas)


def rescatar_del_caddyfile(texto: str) -> dict[str, str]:
    """Las que ya estaban escritas en el bloque, para no perderlas al unificar."""
    trozo = re.search(re.escape(START.split(" (")[0]) + r".*?" + re.escape(END), texto, re.S)
    if not trozo:
        return {}
    return {
        m.group(1): m.group(2)
        for m in re.finditer(r"redir (/\S+) (/\S+) permanent", trozo.group(0))
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    texto = CADDY.read_text(encoding="utf-8")
    mapa = leer()
    rescatadas = {k: v for k, v in rescatar_del_caddyfile(texto).items() if k not in mapa}
    if rescatadas:
        mapa.update(rescatadas)
        print(f"{len(rescatadas)} redirecciones rescatadas del Caddyfile al fichero común")
    # **Manda el fichero vivo.** Una guía puede volver a su nombre de antes: la inglesa de la
    # anafilaxia se renombró en agosto y al regenerarla el 16-sep el título volvió a dar el slug
    # original, así que la redirección vieja apuntaba de la viva a la muerta. Una dirección que
    # existe no se redirige nunca, y una que apunta a algo que ya no existe se tira.
    vivas = paginas_vivas()
    mapa = {k: v for k, v in mapa.items() if k != v and k not in vivas}
    for viejo, destino in list(mapa.items()):
        visto = {viejo}
        while destino not in vivas and destino in mapa and destino not in visto:
            visto.add(destino)
            destino = mapa[destino]
        mapa[viejo] = destino
    mapa = {k: v for k, v in mapa.items() if k != v and v in vivas}

    print(f"{len(mapa)} direcciones viejas apuntando a su guía actual")
    if not args.apply:
        for viejo, nuevo in sorted(mapa.items())[:10]:
            print(f"   {viejo}  →  {nuevo}")
        print("\n(informe; pasa --apply para escribirlo)")
        return 0

    REDIRECTS.parent.mkdir(parents=True, exist_ok=True)
    REDIRECTS.write_text(
        json.dumps(mapa, ensure_ascii=False, indent=1, sort_keys=True), encoding="utf-8"
    )
    viejo_bloque = re.search(re.escape(START.split(" (")[0]) + r".*?" + re.escape(END), texto, re.S)
    nuevo = bloque(mapa)
    if viejo_bloque:
        texto = texto.replace(viejo_bloque.group(0), nuevo, 1)
    else:
        texto = texto.replace(
            "\t# Static site (Astro build)", nuevo + "\n\n\t# Static site (Astro build)", 1
        )
    CADDY.write_text(texto, encoding="utf-8")
    print(f"escritas en {CADDY.relative_to(ROOT)} y en {REDIRECTS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
